# Board
BOARD_ROWS = 3
BOARD_COLS = 3
WIN_SEQUENCE = 3

# Symbols
SYMBOL_X = "X"
SYMBOL_O = "O"
EMPTY_CELL = None

# Screen
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600
HALF_SCREEN = SCREEN_WIDTH // 2

# Drawing
CELL_SIZE = SCREEN_WIDTH // BOARD_COLS
GRID_LINE_WIDTH = 3
SYMBOL_LINE_WIDTH = 4
WIN_LINE_WIDTH = 6

X_COLOR = "yellow"
O_COLOR = "green"
GRID_COLOR = "black"
WIN_COLOR = "red"

SYMBOL_OFFSET_RATIO = 0.25
O_RADIUS_RATIO = 0.25